Feat/basic helm chart support
onebeyond/cuckoojs pull request #26
Opened 2022-11-18 17:06 UTC by w3dani

## What’s the focus of this PR
- Add another schematics for creating a basic helm chart templates
- Important: Not tested against a kubernetes cluster so it could still not be 100% stable, but it's a starting point to keep iteraring
- Updated documentation

## How to review this PR
- Run `schematics @guidesmiths/cuckoojs-schematics:helm`

Before submitting this PR, I made sure:
- [x] The code builds clean without any errors or warnings
- [x] I'm using our guidelines
- [x] I've added unit tests if feasible

**IMPORTANT: This PR has been created from last commit on `feat/pull-request-templates` so please, let's complete first the other branch before reviewing or merging this one**

2022-11-23 12:05 UTC, inigomarquinez requested changes
Some minor changes suggested :)

2022-11-23 12:05 UTC, inigomarquinez commented on packages/@guidesmiths/cuckoojs-schematics/src/helm/schema.json
> +      "x-prompt": "What image you want to config deployment?"
```suggestion
      "x-prompt": "What image do you want to config deployment?"
```

2022-11-23 12:05 UTC, inigomarquinez commented on packages/@guidesmiths/cuckoojs-schematics/src/helm/schema.json
> +      "x-prompt": "What is the CPU limit per pod (specified en 'm' units)?",
```suggestion
      "x-prompt": "What is the CPU limit per pod (specified in 'm' units)?",
```

2022-11-23 12:05 UTC, inigomarquinez commented on packages/@guidesmiths/cuckoojs-schematics/src/helm/schema.json
> +      "x-prompt": "What is the memory limit per pod (specified en 'Mi' units)?",
```suggestion
      "x-prompt": "What is the memory limit per pod (specified in 'Mi' units)?",
```

2022-11-23 12:05 UTC, inigomarquinez commented on packages/@guidesmiths/cuckoojs-schematics/src/helm/schema.json
> +      "x-prompt": "What is the CPU requested per pod (specified en 'm' units)?",
```suggestion
      "x-prompt": "What is the CPU requested per pod (specified in 'm' units)?",
```

2022-11-23 12:05 UTC, inigomarquinez commented on packages/@guidesmiths/cuckoojs-schematics/src/helm/schema.json
> +      "x-prompt": "What is the memory requested per pod (specified en 'Mi' units)?",
```suggestion
      "x-prompt": "What is the memory requested per pod (specified in 'Mi' units)?",
```

2022-11-23 12:05 UTC, inigomarquinez commented on packages/@guidesmiths/cuckoojs-schematics/src/ci/schema.json
> +        "message": "What CI provider you want to set up?",
```suggestion
        "message": "What CI provider do you want to set up?",
```

2022-11-29 08:41 UTC, w3dani commented
> Don't we want to offer the option of using KEDA instead HPA too?

using KEDA means we have to deploy previosly it on the cluster. For me is ok, but I'd go first for the most basic use case that is provided by kubernetes natively

2022-11-29 08:51 UTC, inigomarquinez approved these changes
LGTM!

2022-11-29 08:54 UTC, neodmy approved these changes

2022-11-30 07:53 UTC, merged