feat: add basic-tooling schematic
onebeyond/cuckoojs pull request #66
Opened 2023-05-08 15:42 UTC by neodmy

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-06-19 15:25 UTC, inigomarquinez approved these changes
LGTM!

2023-11-02 10:07 UTC, jonatan-martinez approved these changes

2023-11-13 07:29 UTC, nanotower reviewed
👌

2023-11-21 12:38 UTC, nanotower approved these changes
👍🏻

2023-11-21 12:38 UTC, nanotower commented on packages/@guidesmiths/cuckoojs-schematics/src/basic-tooling/README.md
> +| `skipInstall` | Root folder of your NestJS project                                  | false | string | `.`        |
Is the default value wrong? Shouldn't default as false?

2023-11-21 13:51 UTC, inigomarquinez requested changes
Just one comment

2023-11-21 13:51 UTC, inigomarquinez commented on packages/@guidesmiths/cuckoojs-schematics/src/basic-tooling/basic-tooling.factory.ts
> +		context.logger.info('Adding Husky, Commitlint, Gitignore, Nvmrc...');
Sorry for my TOC, but I think this tools should start by lowercase 😬

2023-11-21 15:02 UTC, inigomarquinez approved these changes

2023-11-21 19:31 UTC, merged